#include "Types/ScoreSaber/Leaderboard.hpp"

DESERIALIZE_METHOD(ScoreSaber, Leaderboard,
    DESERIALIZE_VALUE(Id, id, Int)
    DESERIALIZE_VALUE(SongHash, songHash, String)
    DESERIALIZE_VALUE(SongName, songName, String)
    DESERIALIZE_VALUE(SongSubName, songSubName, String)
    DESERIALIZE_VALUE(SongAuthorName, songAuthorName, String)
    DESERIALIZE_VALUE(LevelAuthorName, levelAuthorName, String)
    DESERIALIZE_VALUE(Difficulty, difficulty, Int)
    DESERIALIZE_VALUE(DifficultyRaw, difficultyRaw, String)
    DESERIALIZE_VALUE(MaxScore, maxScore, Int)
    DESERIALIZE_VALUE(CreatedDate, createdDate, String)
    DESERIALIZE_VALUE(RankedDate, rankedDate, Int)
    DESERIALIZE_VALUE(QualifiedDate, qualifiedDate, Int)
    DESERIALIZE_VALUE(LovedDate, lovedDate, Int)
    DESERIALIZE_VALUE(Ranked, ranked, Int)
    DESERIALIZE_VALUE(Qualified, qualified, Int)
    DESERIALIZE_VALUE(Loved, loved, Int)
    DESERIALIZE_VALUE(MaxPP, maxPP, Int)
    DESERIALIZE_VALUE_2TYPES(Stars, stars, Float, Int)
    DESERIALIZE_VALUE(Plays, plays, Int)
    DESERIALIZE_VALUE(DailyPlays, dailyPlays, Int)
    DESERIALIZE_VALUE(PositiveModifiers, positiveModifiers, Bool)
    //DESERIALIZE_CLASS_OPTIONAL(PlayerScore, playerScore, Int)
    DESERIALIZE_VALUE(CoverImage, coverImage, String)
    //DESERIALIZE_VECTOR_OPTIONAL(Difficulties, difficulties, )
)